version: "3"

services:
    redis-server:      
      image: redis:latest    
    fapi:      
      image: python:3.9    
      build: .      
      restart: always      
      depends_on:        
        - redis-server    
      volumes:     
        - .:/backend    
      ports:       
        - "8080:8080"